language: haskell
ghc:
  - "8.6.1"
cabal: "2.4"
sudo: required

services:
- docker

# Cache .stack for build_times--
addons:
  apt:
    sources:
    - sourceline: 'ppa:tah83/secp256k1'
    packages:
    - libsecp256k1-dev bundler jekyll

cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# From https://github.com/google/proto-lens/blob/5ab25dfeb51f700204db4aa8a9e7fbc5a74ed1e9/.travis.yml#L41-L44
- curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip > protoc-release.zip
- unzip -p protoc-release.zip bin/protoc > $HOME/.local/bin/protoc
- chmod a+x $HOME/.local/bin/protoc
- rm protoc-release.zip
install:
- travis_wait 120 stack --skip-ghc-check setup

- script:
  - cd docs
  - find . -type f -name "*.md" -exec sed -i'' -e 's/.*~~~.*/```/g' {} +
  - JEKYLL_ENV=production bundle exec jekyll build --destination _site

deploy:
  provider: pages
  local-dir: ./docs/_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
